name = "sshx-formal"
version = "0.1.0"
defaultTargets = ["Sshx"]

[leanOptions]
relaxedAutoImplicit = false
autoImplicit = false

[[require]]
name = "trureturing"
git = "https://github.com/the-omega-institute/trureturing.git"
rev = "a2961ff74009447eeafc23a049d5137727b8b716"

[[lean_lib]]
name = "Sshx"
